import React from "react";
import { Compass, Sparkles, MapPin, ArrowRight, Shield, RefreshCw, Plane, HelpCircle, Star } from "lucide-react";
import { motion } from "motion/react";
import LandingHero from "./LandingHero.tsx";

interface DiscoverViewProps {
  onPlanTrip: (destination?: string) => void;
  onLoadPreset: (presetId: string) => void;
}

const DESTINATIONS = [
  {
    id: "trip-kyoto-cherry",
    title: "Kyoto",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80",
    style: "Zen Cultural",
    desc: "Ancient shrines, cherry blossom paths, and pristine sake distilleries."
  },
  {
    id: "trip-paris-luxury",
    title: "Paris",
    country: "France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80",
    style: "Art & Patisserie",
    desc: "Curated Louvre guide, Michelin dining, and boutique atelier tours."
  },
  {
    id: "trip-amalfi-ocean",
    title: "Amalfi Coast",
    country: "Italy",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=600&q=80",
    style: "Coastal Sunset",
    desc: "Private yacht cruises around Capri, lemon gardens, and cliffside suites."
  }
];

const FEATURES = [
  { icon: Sparkles, title: "Multi-Agent AI Generator", desc: "Engineered with Gemini to draft hour-by-hour schedules covering local gastronomy, cultural routes, and logistics." },
  { icon: Compass, title: "Interactive Spatial Maps", desc: "Instantly plots hotels, dining nodes, and daily walking routes onto a custom dark map engine." },
  { icon: Shield, title: "Weather-Responsive Plan", desc: "Real-time adjustments recommending museum archives during rainy forecasts and rooftop lounges on clear sunsets." },
  { icon: RefreshCw, title: "Expense & Budget Ledger", desc: "Tracks costs in real-time by category (Hotel, Transit, Dining) with dynamic bento-style SVG charts." }
];

const FAQS = [
  { q: "How does the AI Travel Planner generate itineraries?", a: "Voyage AI calls Gemini models with structured schemas to map precise travel styles, budgets, and dietary conditions, matching them with vetted coordinates, restaurant cuisines, and seasonal activities." },
  { q: "Can I customize the generated days and activities?", a: "Absolutely! You can edit any activity, add or remove custom expenses, change currency, and chat with Voyage Concierge to modify plans instantly." },
  { q: "Does the application work offline?", a: "Yes. Voyage features a robust offline-first persistence engine. It caching everything locally in your browser. All interactive tools remain 100% functional even when API keys are missing." }
];

const REVIEWS = [
  { name: "Victoria Sterling", role: "Luxury Travel Journalist", text: "Voyage AI has replaced my concierge desk. The Gion sake recommendations and Paris private cruise layouts were absolutely stellar." },
  { name: "Julian Vance", role: "Venture Partner", text: "The structured budget tracking and immediate weather-responsive indoor recommendations made our family Amalfi tour effortless." }
];

export default function DiscoverView({ onPlanTrip, onLoadPreset }: DiscoverViewProps) {
  const [searchVal, setSearchVal] = React.useState("");

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchVal.trim()) {
      onPlanTrip(searchVal.trim());
    }
  };

  return (
    <div className="flex-1 overflow-y-auto bg-earth-bg text-earth-text">
      
      {/* Landing Hero with immersive scenes */}
      <LandingHero 
        searchVal={searchVal} 
        setSearchVal={setSearchVal} 
        handleSearchSubmit={handleSearchSubmit} 
      />

      {/* Featured Destinations Bento Section */}
      <section className="py-20 px-6 max-w-7xl mx-auto space-y-12">
        <div className="text-center md:text-left md:flex md:items-end md:justify-between">
          <div className="space-y-2">
            <h2 className="font-serif italic font-light text-3xl text-earth-text tracking-tight">Curated Masterpiece Presets</h2>
            <p className="text-earth-text/50 text-sm max-w-lg">Sourced by high-end luxury concierges and generated by elite AI models. Click any destination below to load instantly.</p>
          </div>
          <button 
            id="plan-custom-btn"
            onClick={() => onPlanTrip()}
            className="mt-4 md:mt-0 inline-flex items-center gap-2 text-sm font-semibold text-earth-accent hover:text-earth-accent/80 transition-all group"
          >
            <span>Plan Custom Trip</span>
            <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {DESTINATIONS.map((dest, idx) => (
            <motion.div
              id={`preset-card-${dest.title.toLowerCase()}`}
              key={dest.id}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              whileHover={{ y: -6 }}
              className="group cursor-pointer rounded-[32px] overflow-hidden bg-white border border-earth-border hover:border-earth-sage/40 transition-all flex flex-col h-full shadow-sm"
              onClick={() => onLoadPreset(dest.id)}
            >
              <div className="relative h-56 overflow-hidden">
                <img 
                  src={dest.image} 
                  alt={dest.title} 
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/40 to-transparent" />
                <div className="absolute top-4 left-4 px-3 py-1 rounded bg-earth-dark/85 text-[#E6E1D3] font-mono text-[10px] tracking-wider uppercase border border-white/10">
                  {dest.style}
                </div>
                <div className="absolute bottom-4 left-4">
                  <h3 className="font-serif italic text-2xl text-white">{dest.title}</h3>
                  <p className="text-xs text-white/80 flex items-center gap-1 mt-1">
                    <MapPin className="w-3 h-3 text-earth-sage" />
                    <span>{dest.country}</span>
                  </p>
                </div>
              </div>
              <div className="p-6 flex-1 flex flex-col justify-between">
                <p className="text-earth-text/75 text-xs font-light leading-relaxed">{dest.desc}</p>
                <div className="mt-4 pt-4 border-t border-earth-border flex items-center justify-between text-xs font-semibold text-earth-accent group-hover:text-earth-accent/80">
                  <span>Explore Preset Plan</span>
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* AI Features Grid */}
      <section className="bg-earth-light-sage/30 border-y border-earth-border/60 py-20 px-6">
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-4 space-y-6 text-center lg:text-left">
            <div className="inline-flex p-3 rounded-full bg-earth-accent/10 border border-earth-accent/30 text-earth-accent">
              <Sparkles className="w-6 h-6 animate-pulse" />
            </div>
            <h2 className="font-serif italic font-light text-3xl md:text-4xl text-[#4A4A3A] tracking-tight">The AI Agent Architecture</h2>
            <p className="text-earth-text/70 text-sm leading-relaxed font-light">
              Voyage is powered by several cooperative expert agents. Your style agent screens properties, the culinary agent filters seasonal local dishes, while the mapping agent ensures spatial density without long transit delays.
            </p>
            <button 
              id="features-plan-btn"
              onClick={() => onPlanTrip()}
              className="px-6 py-3.5 rounded-full bg-earth-dark hover:bg-earth-dark-accent text-white font-medium text-sm transition-all flex items-center justify-center gap-2 mx-auto lg:mx-0 shadow-sm"
            >
              <span>Initialize Workspace</span>
              <Plane className="w-4 h-4 text-earth-light-sage" />
            </button>
          </div>

          <div className="lg:col-span-8 grid grid-cols-1 md:grid-cols-2 gap-6">
            {FEATURES.map((feat, idx) => {
              const Icon = feat.icon;
              return (
                <div key={idx} className="p-8 rounded-[32px] bg-white border border-earth-border hover:border-earth-sage/40 transition-all space-y-3 shadow-sm">
                  <div className="p-2.5 rounded-full bg-earth-sage/10 border border-earth-sage/20 text-earth-sage w-fit">
                    <Icon className="w-5 h-5" />
                  </div>
                  <h3 className="font-serif italic text-[#4A4A3A] text-lg">{feat.title}</h3>
                  <p className="text-earth-text/70 text-xs font-light leading-relaxed">{feat.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 px-6 max-w-5xl mx-auto space-y-12">
        <div className="text-center space-y-2">
          <h2 className="font-serif italic font-light text-3xl text-earth-text tracking-tight">Vetted by Discerning Voyagers</h2>
          <p className="text-earth-text/50 text-sm">Real reviews from our global private travelers network.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {REVIEWS.map((rev, idx) => (
            <div key={idx} className="p-8 rounded-[32px] bg-white border border-earth-border relative flex flex-col justify-between shadow-sm">
              <p className="text-earth-text/80 text-sm italic font-light leading-relaxed mb-6">"{rev.text}"</p>
              <div className="flex items-center justify-between border-t border-earth-border pt-4">
                <div>
                  <h4 className="font-serif italic font-semibold text-earth-text text-sm">{rev.name}</h4>
                  <p className="text-[10px] font-mono uppercase text-earth-accent mt-0.5">{rev.role}</p>
                </div>
                <div className="flex text-earth-accent">
                  {[...Array(5)].map((_, i) => <Star key={i} className="w-3.5 h-3.5 fill-current" />)}
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ Panel */}
      <section className="py-20 px-6 max-w-3xl mx-auto space-y-12 border-t border-earth-border">
        <div className="text-center space-y-2">
          <h2 className="font-serif italic font-light text-3xl text-earth-text tracking-tight">Frequently Answered Queries</h2>
          <p className="text-earth-text/50 text-sm">Everything you need to know about our smart concierge platform.</p>
        </div>
        <div className="space-y-4">
          {FAQS.map((faq, idx) => (
            <div key={idx} className="p-6 rounded-[32px] bg-white border border-earth-border space-y-3 shadow-sm">
              <div className="flex items-start gap-3">
                <HelpCircle className="w-5 h-5 text-earth-accent shrink-0 mt-0.5" />
                <h3 className="font-serif italic text-earth-text text-base">{faq.q}</h3>
              </div>
              <p className="text-earth-text/75 text-xs font-light leading-relaxed pl-8">{faq.a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Simple elegant Footer */}
      <footer className="py-12 bg-earth-dark text-[#E6E1D3] border-t border-earth-border/20 text-center text-xs font-mono">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4 px-6">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-earth-accent" />
            <span className="font-serif italic text-lg text-white">Voyage AI</span>
          </div>
          <div className="opacity-75">© 2026 VOYAGE AI INC. ALL RIGHTS RESERVED. SECURED VIA DESKTOP-FIRST PRIVILEGE CONTROL.</div>
          <div className="flex gap-4 opacity-75">
            <a href="#" className="hover:text-earth-accent transition-colors">PRIVACY POLICY</a>
            <span>•</span>
            <a href="#" className="hover:text-earth-accent transition-colors">TERMS OF USE</a>
          </div>
        </div>
      </footer>

    </div>
  );
}
